name:
  bank
services:
  database:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: adminbank
      POSTGRES_DB: bank_storage
      POSTGRES_PASSWORD: AdminBank
    volumes:
      - db-data:/var/lib/postgres/data
    networks:
      backend-net:
            aliases:
              - database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
networks:
  backend-net:
    driver: bridge